repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: check-added-large-files
        args: ['--maxkb=1000']
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-yaml

-   repo: https://github.com/ambv/black
    rev: 22.12.0
    hooks:
    -   id: black
        language_version: python3

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    -   id: isort

-   repo: https://github.com/PyCQA/flake8
    rev: 5.0.4
    hooks:
    -   id: flake8
        args: [--config=backend/.flake8]

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910
    hooks:
    -   id: mypy

-   repo: local
    hooks:
    -   id: pytest
        name: pytest
        entry: sh -c 'cd backend && poetry run pytest -n 0' 
        language: system
        types: [python]
        default_stages: [commit]
        require_serial: true

