version: '3.8'

services:
  celery_worker:
    build:
      context: .
      dockerfile: Dockerfile  
    container_name: celery_worker_container
    command: celery -A app.data.celery_app.baes.celery_task worker --loglevel=info
    env_file:
      - .env  
    restart: always

  celery_beat:
    build:
      context: .
      dockerfile: Dockerfile 
    container_name: celery_beat_container
    command: celery -A app.data.celery_app.baes.celery_task beat --loglevel=info
    env_file:
      - .env  
    restart: always
