services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_container
    ports:
      - "8000:8000"
    env_file:
      - .env
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
